### ISSUE TITLE
site broken under HTTPS

### ISSUE THREAD

**Issue by carlwgeorge** [hitchdev/hitchdev.github.io#1]
When viewing [HTTPS://hitchdev.com](https://hitchdev.com), the site looks drastically different than when viewing [HTTP://hitchdev.com](http://hitchdev.com).  I think it's because of mixed HTTP/HTTPS content.  The fonts and stylesheets appear to be hardcoded to load from HTTP URLs.

**Comment by crdoconnor** [comment]
Fixed. Thanks @carlwgeorge.
