### ISSUE TITLE
Incorrect path for 'why not' links

### ISSUE THREAD

**Issue by sd5k** [hitchdev/hitchdev.github.io#2]
The article paths under "Why StrictYAML?" point to 'why', instead of 'why-not'.

**Comment by klmr** [comment]
In addition, the links under http://hitchdev.com/strictyaml/why/ are also all dead.

**Comment by crdoconnor** [comment]
Whoops, thanks guys, will fix this tonight.

**Comment by crdoconnor** [comment]
Fixed. Thanks @klmr and @sd5k for flagging this :+1:
